1.1 Chargement des données
- Votre première tâche consiste à importer les bibliothèques Python nécessaires
pour réaliser ce TD.
- Ensuite, chargez le fichier de données T1.csv dans un DataFrame Pandas nommé
df_wind.
➤ Quelle colonne devez-vous utiliser comme index ? Pourquoi ?

In [1]:
import pandas as pd
import numpy as np

df_wind = pd.read_csv('../dataset/T1.csv', index_col='Date/Time', parse_dates=True)
df_wind.head()

,LV ActivePower (kW),Wind Speed (m/s),Theoretical_Power_Curve (KWh),Wind Direction (°)
Date/Time,,,,
01 01 2018 00:00,380.047791,5.311336,416.328908,259.994904
01 01 2018 00:10,453.769196,5.672167,519.917511,268.641113
01 01 2018 00:20,306.376587,5.216037,390.900016,272.564789
01 01 2018 00:30,419.645905,5.659674,516.127569,271.258087
01 01 2018 00:40,380.650696,5.577941,491.702972,265.674286

1.2 Exploration des données
Dans cette partie, vous allez explorer le jeu de données afin de comprendre sa structure
et son contenu.
- Quelle est la taille du DataFrame chargé ?

In [ ]:
df_wind.shape # (50530, 4)

(50530, 4)

- Affichez les 5 premières lignes et les 5 dernières lignes du DataFrame df_wind.
➤ Que pouvez-vous en déduire ? Pour quelle(s) année(s) l’éolienne a-t-elle
enregistré des données ?

In [ ]:
display(df_wind.head())
display(df_wind.tail())

# On peut en déduire que toutes les éoliennes enregistrés sont toutes de la même année, 2018

,LV ActivePower (kW),Wind Speed (m/s),Theoretical_Power_Curve (KWh),Wind Direction (°)
Date/Time,,,,
01 01 2018 00:00,380.047791,5.311336,416.328908,259.994904
01 01 2018 00:10,453.769196,5.672167,519.917511,268.641113
01 01 2018 00:20,306.376587,5.216037,390.900016,272.564789
01 01 2018 00:30,419.645905,5.659674,516.127569,271.258087
01 01 2018 00:40,380.650696,5.577941,491.702972,265.674286

,LV ActivePower (kW),Wind Speed (m/s),Theoretical_Power_Curve (KWh),Wind Direction (°)
Date/Time,,,,
31 12 2018 23:10,2963.980957,11.404030,3397.190793,80.502724
31 12 2018 23:20,1684.353027,7.332648,1173.055771,84.062599
31 12 2018 23:30,2201.106934,8.435358,1788.284755,84.742500
31 12 2018 23:40,2515.694092,9.421366,2418.382503,84.297913
31 12 2018 23:50,2820.466064,9.979332,2779.184096,82.274620

- Affichez le type de données de chaque colonne du dataset.

In [6]:
df_wind.dtypes

LV ActivePower (kW)              float64
Wind Speed (m/s)                 float64
Theoretical_Power_Curve (KWh)    float64
Wind Direction (°)               float64
dtype: object

- Vérifier la présence de valeurs manquantes.

In [ ]:
df_wind.isnull().sum()

LV ActivePower (kW)              0
Wind Speed (m/s)                 0
Theoretical_Power_Curve (KWh)    0
Wind Direction (°)               0
dtype: int64

- Extraire la colonne Wind Speed sous forme NumPy.

In [ ]:
wind_speed_numpy = df_wind['Wind Speed (m/s)'].to_numpy()
wind_speed_numpy

- Calculez la moyenne et l’écart-type de la variable vitesse du vent (Wind Speed).

In [ ]:
mean_ws = df_wind['Wind Speed (m/s)'].mean()
std_ws = df_wind['Wind Speed (m/s)'].std()
print(f'Moyenne : {mean_ws}')
print(f'Ecart-type : {std_ws}')

1.3 Manipulation des données
- Renommer les colonnes comme suit :
➤ Power au lieu de LV Active Power (kW)
➤ Wind speed au lieu de Wind Speed (m/s)
➤ Theoretical power au lieu de Theoretical Power (kWh)
➤ Wind direction au lieu de Wind Direction (°)

In [ ]:
df_wind.rename(columns={
    'LV ActivePower (kW)': 'Power',
    'Wind Speed (m/s)': 'Wind speed',
    'Theoretical_Power_Curve (KWh)': 'Theoretical power',
    'Wind Direction (°)': 'Wind direction'
}, inplace=True)
df_wind.head()

- Tracez l’évolution de la puissance produite (par intervalles de 10 minutes) en
fonction du temps.

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(15, 6))
plt.plot(df_wind['Power'], color='blue')
plt.title('Evolution de la puissance produite (Power)')
plt.xlabel('Temps')
plt.ylabel('Puissance (kW)')
plt.show()

- Créez une nouvelle colonne appelée loss, correspondant à la différence entre la
puissance théorique et la puissance réellement produite. Puis, tracez la perte
d’énergie en fonction du temps.
➤ Que pouvez-vous en conclure ?

In [ ]:
df_wind['loss'] = df_wind['Theoretical power'] - df_wind['Power']

plt.figure(figsize=(15, 6))
plt.plot(df_wind['loss'], color='red')
plt.title('Evolution de la perte d\'énergie (loss)')
plt.xlabel('Temps')
plt.ylabel('Perte (kW)')
plt.show()

- Une éolienne commence généralement à produire de l’électricité pour une vitesse de
vent comprise entre 12 et 14 km/h (soit 3,3 à 3,8 m/s). Si la vitesse du vent est
supérieure à 3,3 m/s et que la puissance produite est nulle ou négative, on peut
supposer que l’éolienne est en maintenance.
➤ Identifiez les lignes correspondant à cette condition.
➤ Créez un nouveau DataFrame appelé df_wind_nm (sans maintenance), excluant
ces périodes

- Ensuite, tracez la perte d’énergie en fonction du temps pour le DataFrame
df_wind_nm.

- Tracez la différence de perte d’énergie entre les DataFrames avec maintenance
(df_wind) et sans maintenance (df_wind_nm).
➤ Quelle conclusion peut-on en tirer ?

- Tracer la densité de probabilité (KDE) de la puissance et de la vitesse du vent du
DataFrame sans maintenance (df_wind_nm).

On souhaite maintenant créer les composantes x et y du vent à partir de la vitesse
et de la direction du vent.
➤ Les équations utilisées sont : (regarder le PDF)

où :
● Ws représente la vitesse du vent
● Wd représente la direction du vent
Ajoutez ces deux nouvelles colonnes (x et y) au dataset.

- Afin de réduire l’effet du bruit aléatoire, les données doivent être rééchantillonnées.

➤ Créez des DataFrames horaire, journalier, hebdomadaire et mensuel à partir
du DataFrame sans maintenance, en utilisant la moyenne

➤ Utilisez la méthode resample() de Pandas, avec :
○ 'h' pour l’heure
○ 'd' pour le jour
○ 'W' pour la semaine
○ 'ME' pour le mois

➤ Tracez ensuite l’évolution de la puissance produite pour chaque fréquence sous
forme de sous-graphiques(sub-plots).

➤ Vous pouvez également utiliser la fonction asfreq().

➤ Quelle est la différence entre resample() et asfreq() ?

- Remplacez toutes les valeurs NaN par des valeurs interpolées dans les DataFrames horaires journaliers, hebdomadaires et mensuels, en utilisant la fonction interpolate().

- Ajoutez et utilisez une fonction nommée direction afin de créer une nouvelle
colonne catégorielle appelée Direction. Cette fonction prend en entrée la vitesse
du vent.

- Ajoutez cette colonne aux DataFrames journalier, hebdomadaire et mensuel issus du DataFrame sans maintenance (df_wind_nm).

- Tracez l’évolution de la puissance produite du DataFrame horaire durant le mois de décembre. Puis, tracez un second graphique correspondant aux deux dernières semaines de décembre.

- Tracez la puissance moyenne produite à l’échelle hebdomadaire et mensuelle sur un même graphique.

- Appliquez le code fourni.
➤ Que pouvez-vous en conclure ?

- Tracer un pair-plot pour le DataFrame filtré. Quelles conclusions pouvez-vous en
tirer ?

- Tracer la carte de chaleur des corrélations. Que pouvez-vous en conclure ?

★ Quelles variables ont une corrélation plus forte avec la variable ‘Power’ ? Pouvez-vous les lister ?

★ Quelles variables n’ont pas de corrélation avec ‘Power’ ? Pouvez-vous les
lister ?

★ Pourrions-nous obtenir les mêmes résultats si d’autres méthodes de corrélation telles que le « coefficient de corrélation de Kendall Tau » ou la « corrélation par rang de Spearman » étaient utilisées

- Tracer la perte d’énergie en fonction de la direction du vent. Que pouvez-vous en
conclure ?

- Créer un nuage de points 3D avec les variables (x, y, z) : où ‘wind speed’ (vitesse du
vent), ‘wind direction’ (direction du vent) et ‘Power’ (puissance) représentent
respectivement les axes x, y et z. Que pouvez-vous en conclure ?